@host = http://localhost:8000

GET {{host}}/

###
POST {{host}}/prot 
Content-Type: application/json
Authorization: Basic user1:123

{
    "name": "joe",
    "age": 33
}


###
GET {{host}}/items

###
GET {{host}}/items/2

###
PUT {{host}}/items/2
Content-Type: application/json

{
    "id": 1,
    "name": "joana",
    "price": 39.45,
    "is_offer": true
}



###
POST  {{host}}/items
Content-Type: application/json

{
    "name": "manuel",
    "price": 1.23,
    "is_offer": true
}

###
DELETE  {{host}}/items/4

###
POST  {{host}}/items
Content-Type: application/json

{
    "name": "maria",
    "price": 12.35,
    "is_offer": false
}

###
POST  {{host}}/items
Content-Type: application/json

{
    "name": "manuel",
    "price": 23.78,
    "is_offer": false
}

###
DELETE {{host}}/items/4

###
POST  {{host}}/auth/login
Content-Type: application/json

{
    "uid": "demo",
    "pwd": "123"
}

###


@tok1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZW1vIiwiaWQiOjExLCJleHAiOjE3MzgxOTU0MjV9.sP5MFJL-IceVW51FGcnJdGBpy5WwGM1X6TcLrdjxR6Y


POST  {{host}}/auth/chktoken
Content-Type: application/json

{
    "token": "{{tok1}}",
    "error": null
}

###
GET  {{host}}/auth/rnd
Authorization: Bearer {{tok1}}

###
GET  {{host}}/random-int
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZW1vIiwiaWQiOjExLCJleHAiOjE3MjU2MzcxMDV9.uv5RHssvY_8XPyZYpLzSwHA3P2rta35yRC3GpSPCiK8



###
GET {{host}}/api/bonus

###
GET {{host}}/api/bonus/JONES

###
POST {{host}}/api/bonus
Content-Type: application/json

{
  "ename": "Zorro",
  "job": "MANAGER",
  "sal": 1234,
  "comm": 100
}

###
PUT {{host}}/api/bonus/Zorro
Content-Type: application/json

{
  "ename": "Zorro",
  "job": "MANAGER",
  "sal": 5432,
  "comm": 200
}

###
DELETE {{host}}/api/bonus/Zorro

###
